### ISSUE TITLE
voice control

### ISSUE THREAD

**Issue by icantthinkofacreativeusername** [icantthinkofacreativeusername/ourcontributiontoblindmusicians#4]
Check if it is viable in android sdk, or potentially iOS

- Menu navigation

**Comment by eight0153** [comment]
There's an open source voice recognition API that works on android called [CMUSphinx](https://cmusphinx.github.io/wiki/tutorialandroid/)
Apparently this works better than the android platform speech recognition because the android one requires an internet connection and if you are using it a lot it uses a lot of battery + data and CMUSphinx works offline.
